### ISSUE TITLE
Issues reading str->str std::map structures in branch

### ISSUE THREAD

**Issue by zinebaly** [scikit-hep/uproot#431] opened 2020-01-07 12:08 UTC
First of all: happy new year! Thank you for your time and priceless help :)

Here is my issue:
When I try to read a root file header, an uproot error is raised. Here is how I proceed

```Python
file = uproot.open(my_root_file)
file.keys()
>>> [b'Head;1',
 b'META;1',
 b'E;1',
 b'KM3NET_TIMESLICE;1',
 b'KM3NET_TIMESLICE_L0;1',
 b'KM3NET_TIMESLICE_L1;1',
 b'KM3NET_TIMESLICE_L2;1',
 b'KM3NET_TIMESLICE_SN;1',
 b'KM3NET_EVENT;1',
 b'KM3NET_SUMMARYSLICE;1']
```
to read the header info, I type:

```Python
tree = file[b'Head;1']
```

which raises the following error:

```Python
NotImplementedError: 

Unimplemented streamer type: TStreamerSTL

members: {'_classversion': 4, '_fOffset': 0, '_fName': b'map<string,string>', '_fTitle': b'', '_fType': 500, '_fSize': 0, '_fArrayLength': 0, '_fArrayDim': 0, '_fMaxIndex': array([0, 0, 0, 0, 0], dtype=int32), '_fTypeName': b'map<string,string>', '_fXmin': 0.0, '_fXmax': 0.0, '_fFactor': 0.0, '_fSTLtype': 4, '_fCtype': 61}

file contents:

00000020  40 00 02 d4 40 09 00 00  4f d9 d7 42 00 00 00 22  |@...@...O..B..."|
00000040  40 00 01 17 00 09 03 44  41 51 03 50 44 46 08 58  |@......DAQ.PDF.X|
00000060  53 65 63 46 69 6c 65 03  63 61 6e 08 63 61 6e 5f  |SecFile.can.can_|
00000100  75 73 65 72 0c 63 6f 6f  72 64 5f 6f 72 69 67 69  |user.coord_origi|
00000120  6e 06 63 75 74 5f 69 6e  06 63 75 74 5f 6e 75 0b  |n.cut_in.cut_nu.|
00000140  63 75 74 5f 70 72 69 6d  61 72 79 0b 63 75 74 5f  |cut_primary.cut_|
00000160  73 65 61 6d 75 6f 6e 05  64 65 63 61 79 08 64 65  |seamuon.decay.de|
00000200  74 65 63 74 6f 72 07 64  72 61 77 69 6e 67 09 65  |tector.drawing.e|
00000220  6e 64 5f 65 76 65 6e 74  09 67 65 6e 68 65 6e 63  |nd_event.genhenc|
00000240  75 74 06 67 65 6e 76 6f  6c 04 6b 63 75 74 08 6c  |ut.genvol.kcut.l|
```
To have an overview of the header's data, here is an alternative way of reading the file header (using an internal software package - aa- based on ROOT): 

```Python

In [1]: import ROOT, aa                                                                                                           
loading root....  /pbs/throng/km3net/software/root/6.18.04
loading /pbs/throng/km3net/software/aanet/2.0.0/lib/libaaevt.so ... ok (0.52 s.)
loading /pbs/throng/km3net/software/aanet/2.0.0/lib/libaastro.so ... ok (0.03 s.)

In [2]: f = ROOT.EventFile("numucc.root")                                                                                         

In [3]: print(f.header)                                                                                                           
start_run: 1
DAQ: 394
PDF: 4      58
XSecFile: 
can: 0 1027 888.4
can_user: 0.00 1027.00  888.40
coord_origin: 0 0 0
cut_in: 0 0 0 0
cut_nu: 100 1e+08 -1 1
cut_primary: 0 0 0 0
cut_seamuon: 0 0 0 0
decay: doesnt happen
detector: NOT
drawing: Volume
genhencut: 2000 0
genvol: 0 1027 888.4 2.649e+09 100000
kcut: 2
livetime: 0 0
model: 1       2       0       1      12
muon_desc_file: 
ngen: 0.1000E+06
norma: 0 0
nuflux: 0       3       0 0.500E+00 0.000E+00 0.100E+01 0.300E+01
physics: GENHEN 7.2-220514 181116 1138
seed: GENHEN 3  305765867         0         0
simul: JSirene 11012 11/17/18 07
sourcemode: diffuse
spectrum: -1.4
target: isoscalar
usedetfile: false
xlat_user: 0.63297
xparam: OFF
zed_user: 0.00 3450.00
end_event:


In [4]: f.header.get_line("can")                                                                                                  
Out[4]: '0 1027 888.4'
```
the header data is usually accessed using a `std::str->std::str` map. 

Is it possible to access the header data using uproot? 

root file mentioned above:
[numucc.root.zip](https://github.com/scikit-hep/uproot/files/4030411/numucc.root.zip)

I would like to ping @tamasgal

**Comment by jpivarski** [comment] 2020-01-07 18:25
In the `Head` streamer, the attribute that is a map is named after the type (is `Head` a `typedef` or something?):

```
StreamerInfo for class: Head, version=2, checksum=0x14a3f174
  TObject         BASE            offset=  0 type=66 Basic ROOT object
  map<string,string> map<string,string> offset=  0 type=500 
```

so the field name within an instance of `Head` is `_map_3c_string_2c_string_3e_`. Admittedly, that's a strange name, but the data's there (as a dict of bytestrings to bytestrings):

```python
>>> head = file["Head"]
>>> for n, x in head._map_3c_string_2c_string_3e_.items():
...     print("{:15s} {}".format(n.decode("utf-8"), x))
... 
DAQ             b'394'
PDF             b'4      58'
XSecFile        b''
can             b'0 1027 888.4'
can_user        b'0.00 1027.00  888.40'
coord_origin    b'0 0 0'
cut_in          b'0 0 0 0'
cut_nu          b'100 1e+08 -1 1'
cut_primary     b'0 0 0 0'
cut_seamuon     b'0 0 0 0'
decay           b'doesnt happen'
detector        b'NOT'
drawing         b'Volume'
end_event       b''
genhencut       b'2000 0'
genvol          b'0 1027 888.4 2.649e+09 100000'
kcut            b'2'
livetime        b'0 0'
model           b'1       2       0       1      12'
muon_desc_file  b''
ngen            b'0.1000E+06'
norma           b'0 0'
nuflux          b'0       3       0 0.500E+00 0.000E+00 0.100E+01 0.300E+01'
physics         b'GENHEN 7.2-220514 181116 1138'
seed            b'GENHEN 3  305765867         0         0'
simul           b'JSirene 11012 11/17/18 07'
sourcemode      b'diffuse'
spectrum        b'-1.4'
start_run       b'1'
target          b'isoscalar'
usedetfile      b'false'
xlat_user       b'0.63297'
xparam          b'OFF'
zed_user        b'0.00 3450.00'
```

Try this solution on other files to be sure that I haven't "overfitted" to this one example. When you give me the okay on the PR (#432), I'll merge it.

**Comment by zinebaly** [comment] 2020-01-08 13:18
Thank you for your quick reply. 

Here are the results of the tests I performed: 
* file 1: 
```Python
fobj1 = uproot.open(f1)
fobj1.keys()

>>> [b'Head;1', b'META;1', b'E;21', b'E;20']

head1 = fobj1["Head"]
for n, x in head1._map_3c_string_2c_string_3e_.items():
    print("{:15s} {}".format(n.decode("utf-8"), x))

>>> DAQ             b' 21584.6'
```
The expected result is:
```Python

In [1]: import ROOT, aa                                                                                                                                                                     
loading root....  /pbs/throng/km3net/software/root/6.18.04
loading /pbs/throng/km3net/software/aanet/2.0.0/lib/libaaevt.so ... ok (0.53 s.)
loading /pbs/throng/km3net/software/aanet/2.0.0/lib/libaastro.so ... ok (0.03 s.)

In [2]: f1 = ROOT.EventFile(f1)                                                                                                                                             

In [3]: print(f1.header)                                                                                                                                                                     
DAQ:  21584.6
end_event:
```
So file 1 works! 

* file 2:



```Python
fobj2 = uproot.open(f2)
fobj2.keys()

>>> [b'META;1',
 b'EVT;7',
 b'EVT;6',
 b'Head;1',
 b'E;5',
 b'E;4',
 b'JTRIGGER::JTriggerParameters;1',
 b'KM3NET_EVENT;2',
 b'KM3NET_EVENT;1',
 b'KM3NET_SUMMARYSLICE;12',
 b'KM3NET_SUMMARYSLICE;11',
 b'KM3NET_TIMESLICE;1',
 b'KM3NET_TIMESLICE_L0;1',
 b'KM3NET_TIMESLICE_L1;1',
 b'KM3NET_TIMESLICE_L2;1',
 b'KM3NET_TIMESLICE_SN;1']

head2 = fobj2["Head"]
for n, x in head2._map_3c_string_2c_string_3e_.items():
    print("{:15s} {}".format(n.decode("utf-8"), x))

>>> can             b' 0 466.1 299.8'
coord_origin    b' 0 0 0 '
cut_in          b' 1 500000 -1 -0.087156'
livetime        b' 2510 3'
norma           b' 0 1e+06'
physics         b' HEMAS-DPM 07.01  '
propag          b'MUSIC seawater   02.03'
seabottom       b' 2425'
seed            b'MUPAGE-MT19937   3  118553413  0  0'
simul           b' JSirene 12.0.0-alpha.3 10/03/19 15:46:23'
start_run       b' 1'

```
The expected result is:
```Python
In [1]: import ROOT, aa                                                                                                                                                                     
loading root....  /pbs/throng/km3net/software/root/6.18.04
loading /pbs/throng/km3net/software/aanet/2.0.0/lib/libaaevt.so ... ok (0.53 s.)
loading /pbs/throng/km3net/software/aanet/2.0.0/lib/libaastro.so ... ok (0.03 s.)

In [2]: f2 = ROOT.EventFile(f2)                                                                                                                                             

In [3]: print(f2.header)
>>> start_run:  1
DAQ:  18781.6
can:  0 466.1 299.8
coord_origin:  0 0 0 
cut_in:  1 500000 -1 -0.087156
livetime:  2510 3
norma:  0 1e+06
physics:  HEMAS-DPM 07.01  
propag: MUSIC seawater   02.03
seabottom:  2425
seed: MUPAGE-MT19937   3  118553413  0  0
simul:  JSirene 12.0.0-alpha.3 10/03/19 15:46:23
end_event:
```

We can see that uproot did not print the line `DAQ:  18781.6` from the header. 

* file 3:

```Python
fobj3 = uproot.open(f3)
fobj3.keys()

>>> [b'Header;1', b'E;1']

head3 = fobj3["Header"]
```
In this 3rd case, an error is raised:

```Python
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-42-4c806774eaf2> in <module>
----> 1 head3 = f3['Header']
      2 
      3 # In [1]: import ROOT, aa
      4 # loading root....  /pbs/throng/km3net/software/root/6.18.04
      5 # loading /pbs/throng/km3net/software/aanet/2.0.0/lib/libaaevt.so ... ok (0.53 s.)

~/km3net/uproot/uproot/uproot/rootio.py in __getitem__(self, name)
    223 
    224     def __getitem__(self, name):
--> 225         return self.get(name)
    226 
    227     def __len__(self):

~/km3net/uproot/uproot/uproot/rootio.py in get(self, name, cycle)
    357 
    358             if last is not None:
--> 359                 return last.get()
    360             elif cycle is None:
    361                 raise _KeyError("not found: {0}\n in file: {1}".format(repr(name), self._context.sourcepath))

~/km3net/uproot/uproot/uproot/rootio.py in get(self, dismiss)
   1021 
   1022         try:
-> 1023             return _classof(self._context, self._fClassName).read(self._source, self._cursor.copied(), self._context, self)
   1024         finally:
   1025             if dismiss:

~/km3net/uproot/uproot/uproot/rootio.py in read(cls, source, cursor, context, parent)
    960             context = context.copy()
    961         out = cls.__new__(cls)
--> 962         out = cls._readinto(out, source, cursor, context, parent)
    963         out._postprocess(source, cursor, context, parent)
    964         return out

~/km3net/uproot/uproot/uproot/rootio.py in _readinto(cls, self, source, cursor, context, parent, asclass)

~/km3net/uproot/uproot/uproot/rootio.py in _mapstrstr(source, cursor)
    464     size = cursor.field(source, _mapstrstr._int32)
    465     cursor.skip(6)
--> 466     keys = [cursor.string(source) for i in range(size)]
    467     cursor.skip(6)
    468     values = [cursor.string(source) for i in range(size)]

~/km3net/uproot/uproot/uproot/rootio.py in <listcomp>(.0)
    464     size = cursor.field(source, _mapstrstr._int32)
    465     cursor.skip(6)
--> 466     keys = [cursor.string(source) for i in range(size)]
    467     cursor.skip(6)
    468     values = [cursor.string(source) for i in range(size)]

~/km3net/uproot/uproot/uproot/source/cursor.py in string(self, source)
     71         start = self.index
     72         stop = self.index = start + length
---> 73         return source.data(start, stop).tostring()
     74 
     75     def cstring(self, source):

~/km3net/uproot/uproot/uproot/source/memmap.py in data(self, start, stop, dtype)
     42 
     43         if stop > len(self._source):
---> 44             raise IndexError("indexes {0}:{1} are beyond the end of data source {2}".format(len(self._source), stop, repr(self.path)))
     45 
     46         if dtype is None:

IndexError: indexes 76914:919723173 are beyond the end of data source '/home/zineb/km3net/km3net/km3io/tests/samples/aanet_v2.0.0.root'
```

I attached file 3.

[file3.zip](https://github.com/scikit-hep/uproot/files/4035325/file3.zip)

@tamasgal

**Comment by tamasgal** [comment] 2020-01-08 13:21
A little information about the `Head` class, it is defined like this:

```c++
struct Head : public TObject, map<string, string>
```
and the mentioned `get_line(string key)` method is simply this:

```c++
  string& get_line( string key ) 
  {
    return map<string, string>::operator[]( key );
  }
```

So it's not much actually...

**Comment by jpivarski** [comment] 2020-01-10 17:01
@zinebaly @tamasgal Although it's happening in a very different place in uproot's deserialization, this problem is similar to the one @tamasgal is facing in #433. It's a matter of reverse-engineering a data type that we hadn't encountered until now.

The initial implementation (PR #432) assumes the following pattern, based on the first file:

   1. skip 12 bytes;
   2. deserialize a 4-byte integer as `size`;
   3. skip 6 bytes;
   4. deserialize `size` strings as `keys`;
   5. skip 6 bytes;
   6. deserialize `size` strings as `values`;
   7. the desired dict is `dict(zip(keys, values))`.

However, looking at file 3, which seems to have one key-value pair in it, the pattern should be:

   1. skip 6 bytes;
   2. deserialize a 4-byte integer as `size`;
   3. deserialize `size` strings as `keys`;
   4. deserialize `size` strings as `values`;
   5. the desired dict is `dict(zip(keys, values))`.

That is, the following diff makes the PR work for file 3 and not for file 1:

```diff
diff --git a/uproot/rootio.py b/uproot/rootio.py
index 40545ce..9f8bda1 100644
--- a/uproot/rootio.py
+++ b/uproot/rootio.py
@@ -460,11 +460,12 @@ def _nametitle(source, cursor):
     return name, title
 
 def _mapstrstr(source, cursor):
-    cursor.skip(12)
-    size = cursor.field(source, _mapstrstr._int32)
+    # cursor.skip(12)
     cursor.skip(6)
+    size = cursor.field(source, _mapstrstr._int32)
+    # cursor.skip(6)
     keys = [cursor.string(source) for i in range(size)]
-    cursor.skip(6)
+    # cursor.skip(6)
     values = [cursor.string(source) for i in range(size)]
     return dict(zip(keys, values))
```

Something simple is happening here: 6 bytes is a typical `TObject` header, and one of the files is getting extra headers that the other one isn't. This could be related to some information in the bytes I'm currently skipping.

Since you two are pushing the boundaries of complex types for uproot to deserialize, maybe you should investigate it at the byte level. Uproot makes this much easier than it might initially sound—it gets the file pointer (`Cursor`) to the part of the file that has to be reverse-engineered, which is 98% of the work: knowing what you can ignore. Throughout the uproot codebase are examples of similar deserialization problems and their solutions: the same themes come up again and again (like that 6-byte header).

**Comment by tamasgal** [comment] 2020-01-11 09:38
Alright, I'll take over from here. Thanks!

**Comment by jpivarski** [comment] 2020-01-11 16:38
Thanks!

**Comment by tamasgal** [comment] 2020-01-11 18:34
Can you please assign me? 😉

**Comment by tamasgal** [comment] 2020-01-13 14:19
@zinebaly are you sure that `uproot` did not print the line with `DAQ: ...` for the first file? I cannot reproduce it, for me it prints everything in the header:


```
[ins] In [1]: import uproot                                                                                           

[ins] In [2]: f = uproot.open("mcv6.0test.mupage_10G.sirene.jterbr00005971.jchain.aanet.2143.root")                   

[ins] In [5]: for n, x in f['Head']._map_3c_string_2c_string_3e_.items(): 
         ...:     print("{:15s} {}".format(n.decode("utf-8"), x)) 
         ...:                                                                                                         
<uproot.source.compressed.CompressedSource object at 0x7ff80165f250>
Now at index: 16, origin: -37
DAQ             b' 18781.6'
can             b' 0 466.1 299.8'
coord_origin    b' 0 0 0 '
cut_in          b' 1 500000 -1 -0.087156'
livetime        b' 2510 3'
norma           b' 0 1e+06'
physics         b' HEMAS-DPM 07.01  '
propag          b'MUSIC seawater   02.03'
seabottom       b' 2425'
seed            b'MUPAGE-MT19937   3  118553413  0  0'
simul           b' JSirene 12.0.0-alpha.3 10/03/19 15:46:23'
start_run       b' 1'
```

...ignore the debug messages

**Comment by tamasgal** [comment] 2020-01-13 15:17
I did not get really far but I'd like to make a short summary... I created binary dumps from the chunks of the `CompressedSource` and `MemmapSource` objects to investigate the data with a hex editor for all three files.

I was not able to reproduce the observation of @zinebaly where the first key/value pair was missed, so I basically concluded that we have two types of "header" implementations. This is also backed by the fact that one is called `"Head"` and the other `"Header"`. The files with `"Head"` are readable with @jpivarski's current PR and the other is (as it turned out) coming from another piece of software which was involved in the ROOT file creation.

I am now searching for the code to see how the class is implemented :see_no_evil:

**Comment by tamasgal** [comment] 2020-01-13 15:33
I found the legacy code... For the sake of completeness, this is the class which generated the `Header` entry:

```c++
class Header : public TObject {
private:
  int number_of_headers;   //!< number of files 'chained'
public:
  const int& getNumberOfHeaders() const { return number_of_headers; }

  //
  // ---------------------------------------------------------------------------
  // In order to find the data member corresponding to the input tag and 
  // to preserve the original tag on output, 
  // the data member and the class have to have the same name.
  // The namespace is used to avoid name clash of class 'merge' and 
  // to distinguish class name and data member name.
  // ---------------------------------------------------------------------------
  //
  MONTE_CARLO::XSecFile        XSecFile;
  MONTE_CARLO::detector        detector;
  MONTE_CARLO::muon_desc_file  muon_desc_file;
  MONTE_CARLO::node            node;
  MONTE_CARLO::target          target;
  MONTE_CARLO::drawing         drawing;
  MONTE_CARLO::physics         physics;
  MONTE_CARLO::simul           simul;
  MONTE_CARLO::cut_primary     cut_primary;
  MONTE_CARLO::cut_seamuon     cut_seamuon;
  MONTE_CARLO::cut_in          cut_in;
  MONTE_CARLO::cut_nu          cut_nu;
  MONTE_CARLO::start_run       start_run;
  MONTE_CARLO::spectrum        spectrum;
  MONTE_CARLO::PM1_type_area   PM1_type_area;
  MONTE_CARLO::PDF             PDF;
  MONTE_CARLO::model           model;
  MONTE_CARLO::can             can;
  MONTE_CARLO::genvol          genvol;
  MONTE_CARLO::merge           merge;
  MONTE_CARLO::coord_origin    coord_origin;
  MONTE_CARLO::genhencut       genhencut;
  MONTE_CARLO::k40             k40;
  MONTE_CARLO::norma           norma;
  MONTE_CARLO::v_seed          seed;
  MONTE_CARLO::livetime        livetime;
  MONTE_CARLO::v_flux          flux;

  Header() : 
    number_of_headers(0) 
  {}

  Header(std::istream& in) : 
    number_of_headers(0) 
  { 
    Streamer(in); 
  }

  Header(TChain& chain) : 
    number_of_headers(0)
  {
    TIter next(chain.GetListOfFiles());

    for (TChainElement* i = NULL; (i = (TChainElement*) next()) != NULL; )
      Add(i->GetTitle());
  }

  virtual ~Header() {}

  // ... some irrelevant helper methods

  ClassDef(Header,3);
};
```

**Comment by tamasgal** [comment] 2020-01-13 15:59
@jpivarski we can close this issue by merging your https://github.com/scikit-hep/uproot/pull/432 as the `Header` is not a `str->str` map therefore unrealted.

Thanks!

**Comment by jpivarski** [comment] 2020-01-13 16:21
If `Header` is not a `str->str` map, why is it triggering the `_mapstrstr` function? It has to be hitting this case:

https://github.com/scikit-hep/uproot/blob/aed63ce4aecc930db88ef922439ea0c88b768d10/uproot/rootio.py#L865-L866

so the type name of the streamer is `"map<string,string>"`. If that's because `Header` is "faking it," then we can just merge PR #432 because it's the right solution, only not working for "fake" classes. If it's a legitimate way that `str->str` maps can be serialized, then merging PR #432 would be introducing a bug: legitimate files would usually move the `Cursor` off the end of the file.

Is there something "wrong" or "fake" about the `Header` class, so that I don't need to worry that it's a legitimate case?

**Comment by tamasgal** [comment] 2020-01-13 17:06
Ouf, that's a good point. I was too fast with my conclusion.

The "old" `Header` class is used by the new framework which introduced the currently used `Head` class (in file 1 and 2). I am truly confused why `Header` is shown as a `map<string,string>` in file 3, however, I found this code which implements the `read(Head& h1, Header& h2)` method.

```c++
struct _TDumpToHead : public TMemberInspector 
{
  Head& h;

  _TDumpToHead(Head& h) : h(h) {}

  void Inspect(TClass *cl, const char *pname, const char *mname, const void *addr)
  {
    TDataMember *member = cl->GetDataMember(mname);
    if (!member) return; 

    string type     = member->GetFullTypeName();
    string field    = mname;
    string key      = replace_all( pname , ".","");
  
    if ( key == "" ) std::swap( key, field);

    string value = "";
    if ( member->IsBasic() ) value = member->GetDataType()->AsString( (void*) addr );
    
    if ( value == "true"   ) value = "1"; 
    if ( value == "false"  ) value = "0";
    if ( type == "string"  ) value = *( (string*) addr );
    
    if ( field == "fUniqueID" || field == "fBits" || field == "isDefined_") return; // not interested

    if ( field =="buffer" || field == "") 
      {
	h.get_line( key ) = value;
      }
    else if (value !="")
      {
	h.set_field( key, field, value);
      }
  }

}; 


void read(Head& h, const Header& antcc_header )
{
  _TDumpToHead d(h);
  (const_cast<Header&>(antcc_header)).ShowMembers( d );
}
```

So it does a `const_cast<Head&>` (the one with `map<string,string`) from the `.ShowMembers()` method. There is some manual hacking of the ROOT stuff too, maybe you can tell more with all your experience.
Is that the reason why `Header` is propagated as class name and it is really some kind of a fake object from the `static_cast` which is dumped into the ROOT file?

**Comment by tamasgal** [comment] 2020-01-20 13:36
@jpivarski I think we should just merge your https://github.com/scikit-hep/uproot/pull/432 and close this as it to works fine for the normal case of map-str-str-derived classes. The other class is a bit hackish anyways, I don't think we will see something like this in the wild...

**Comment by jpivarski** [comment] 2020-01-20 17:32
I'll do that. (Testing after resolve-conflict now, will merge directly afterward.)

**Closed by jpivarski** 2020-01-20 17:32 UTC

**Comment by tamasgal** [comment] 2020-01-20 17:35
Many thanks! @zinebaly you can now go ahead with `km3io` 😉
