### ISSUE TITLE
Name mismatch for PositionVector3D streamer

### ISSUE THREAD

**Issue by chrisburr** [scikit-hep/uproot#448] opened 2020-02-10 04:31 UTC
Yet another fun streamer naming thing... 😉

When opening a file from the CMS opendata, loading the `Tree` object fails with a `KeyError`. This seems to be because the expected key in `streamerinfosmap` is:

`b'ROOT::Math::PositionVector3D<ROOT::Math::Cartesian3D<double> >'`

I can work around it by hacking the key to be:

`b'ROOT::Math::PositionVector3D<ROOT::Math::Cartesian3D<double>,ROOT::Math::DefaultCoordinateSystemTag>'`

## Full reproducer
```python
In [1]: import uproot
   ...: f = uproot.open('root://eospublic.cern.ch//eos/opendata/cms/Run2010B/MuOnia/AOD/Apr21ReReco-v1/0000/02186E3C-D277-E011-8A05-00215E21D516.root')
   ...: tree = f['Events']
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-1-6b196f960e9d> in <module>
      1 import uproot
      2 f = uproot.open('root://eospublic.cern.ch//eos/opendata/cms/Run2010B/MuOnia/AOD/Apr21ReReco-v1/0000/02186E3C-D277-E011-8A05-00215E21D516.root')
----> 3 tree = f['Events']

~/miniconda3/envs/d2hll/lib/python3.7/site-packages/uproot/rootio.py in __getitem__(self, name)
    223
    224     def __getitem__(self, name):
--> 225         return self.get(name)
    226
    227     def __len__(self):

~/miniconda3/envs/d2hll/lib/python3.7/site-packages/uproot/rootio.py in get(self, name, cycle)
    357
    358             if last is not None:
--> 359                 return last.get()
    360             elif cycle is None:
    361                 raise _KeyError("not found: {0}\n in file: {1}".format(repr(name), self._context.sourcepath))

~/miniconda3/envs/d2hll/lib/python3.7/site-packages/uproot/rootio.py in get(self, dismiss)
   1024
   1025         try:
-> 1026             return _classof(self._context, self._fClassName).read(self._source, self._cursor.copied(), self._context, self)
   1027         finally:
   1028             if dismiss:

~/miniconda3/envs/d2hll/lib/python3.7/site-packages/uproot/rootio.py in read(cls, source, cursor, context, parent)
    964         out = cls.__new__(cls)
    965         out = cls._readinto(out, source, cursor, context, parent)
--> 966         out._postprocess(source, cursor, context, parent)
    967         return out
    968

~/miniconda3/envs/d2hll/lib/python3.7/site-packages/uproot/tree.py in _postprocess(self, source, cursor, context, parent)
    287
    288         for branch in self._fBranches:
--> 289             self._attachstreamer(branch, context.streamerinfosmap.get(getattr(branch, "_fClassName", None), None), context.streamerinfosmap, False)
    290
    291         self._branchlookup = {}

~/miniconda3/envs/d2hll/lib/python3.7/site-packages/uproot/tree.py in _attachstreamer(self, branch, streamer, streamerinfosmap, isTClonesArray)
    279                     pass
    280
--> 281                 self._attachstreamer(subbranch, submembers.get(name, None), streamerinfosmap, isTClonesArray)
    282
    283     def _postprocess(self, source, cursor, context, parent):

~/miniconda3/envs/d2hll/lib/python3.7/site-packages/uproot/tree.py in _attachstreamer(self, branch, streamer, streamerinfosmap, isTClonesArray)
    266                         base, name = name[:index], name[index + 1:]
    267                         if base in submembers and isinstance(submembers[base], digDeeperTypes):
--> 268                             submembers = streamerinfosmap[submembers[base]._fTypeName.rstrip(b"*")].members
    269
    270                 try:

KeyError: b'ROOT::Math::PositionVector3D<ROOT::Math::Cartesian3D<double> >'
```

**Comment by jpivarski** [comment] 2020-02-10 11:36
Is it a space (or lack thereof) before a closing `>`?

I always thought that was going to be trouble. Old versions of C++ needed that space because otherwise `>>` would be interpreted as a shift operator, and a lot of templates class names are used as string -based lookups in ROOT.

I wonder if I'm going to have to make the key lookup a regular expression. There are a lot of places where that might need to happen...

**Comment by chrisburr** [comment] 2020-02-10 12:24
It's worse. It's missing the second template parameter entirely, namely: `,ROOT::Math::DefaultCoordinateSystemTag`

My horrible workaround commit is this:
https://github.com/chrisburr/uproot/commit/2de785f9de4f534849ad975676a36e2e09af5c74

**Comment by jpivarski** [comment] 2020-02-10 12:46
Oh, okay. On the one hand, it's good that ROOT is maintaining the space-convention when closing templates, even though it's not needed in the programming language, because it's been "burned into" many old files.

The problem of missing a template parameter sounds like the an update to the class definition. By changing its name, this should be treated as a whole new class. Is the class name in the streamers inconsistent with the class name in the body of the file? Maybe that was caused by an `hadd` process that had a different ROOT version from the CMSSW process that originally created the file. (There are other issues where `hadd` changed the set of streamers available, which motivated stepping back and identifying some by string name, rather than integer codes, because the string names were more universally reliable.)

If that's the case, this is a localized bug, something that affects these classes in a particular combination of ROOT versions. I'd be willing to adopt your hack in a formalized way: there are other places where I gave up on exceptions to the general rules and wrote class-specific customizations (by class name). This is affecting the `attachstreamers` part of tree.py, which is a preparatory step for associating a default interpretation from `uproot.interp.auto`. Maybe we could put a name-mapping in `uproot.interp.auto`, just a dict to use as a fall-back if the actual names are not found. Then instead of naming specific fall-backs in the `attachstreamers` function, `attachstreamers` could try the real class name first, then see if there's a match in `uproot.interp.auto.streamer_aliases` (a single hashmap-lookup for every class), and then fail if nothing was found.

This adds an operation to every branch of every TTree that's opened, so it's potentially a performance issue, but I think a single hashmap-lookup (of what is likely to remain a small hashmap) wouldn't be much compared to the steps that are already there. CMSSW files are among the biggest in terms of TTree metadata, so you're in a good position to see if it does make much of a difference (to local files; remote adds another confounding effect).

What do you think?

**Comment by chrisburr** [comment] 2020-02-10 14:58
I think I follow and have something locally. I've ran into a second issue with the autogenerated class. I've hacked it to show the traceback below correctly but it's functionally the same as what's in master. Is the best option just to clone what's in the global `classes` dictionary that is used in:

```python
exec(compile(codestr, "<generated from TStreamerInfo {0} at 0x{1:012x}>".format(repr(classname), id), "exec"), classes)
```

### Traceback

```python
In [2]: a = tree.arrays()
---------------------------------------------------------------------------
_NotNumerical                             Traceback (most recent call last)
~/Development/uproot/uproot/interp/auto.py in interpret(branch, awkwardlib, swapbytes, cntvers, tobject, speedbump)
    221             else:
--> 222                 fromdtype = _leaf2dtype(branch._fLeaves[0], awkward).newbyteorder(">")
    223

~/Development/uproot/uproot/interp/auto.py in _leaf2dtype(leaf, awkward)
     97     elif classname == "TLeafElement":
---> 98         return _ftype2dtype(leaf._fType, awkward)
     99     else:

~/Development/uproot/uproot/interp/auto.py in _ftype2dtype(fType, awkward)
     66     else:
---> 67         raise _NotNumerical
     68

_NotNumerical:

During handling of the above exception, another exception occurred:

_NotNumerical                             Traceback (most recent call last)
~/Development/uproot/uproot/interp/auto.py in interpret(branch, awkwardlib, swapbytes, cntvers, tobject, speedbump)
    317                     try:
--> 318                         fromdtype = _ftype2dtype(branch._streamer._fCtype, awkward)
    319                         if swapbytes:

~/Development/uproot/uproot/interp/auto.py in _ftype2dtype(fType, awkward)
     66     else:
---> 67         raise _NotNumerical
     68

_NotNumerical:

During handling of the above exception, another exception occurred:

NameError                                 Traceback (most recent call last)
<ipython-input-2-81a3223740c9> in <module>
----> 1 a = tree.arrays()

~/Development/uproot/uproot/tree.py in arrays(self, branches, outputtype, namedecode, entrystart, entrystop, flatten, flatname, awkwardlib, cache, basketcache, keycache, executor, blocking)
    515     def arrays(self, branches=None, outputtype=dict, namedecode=None, entrystart=None, entrystop=None, flatten=False, flatname=None, awkwardlib=None, cache=None, basketcache=None, keycache=None, executor=None, blocking=True):
    516         awkward = _normalize_awkwardlib(awkwardlib)
--> 517         branches = list(self._normalize_branches(branches, awkward))
    518         for branch, interpretation in branches:
    519             if branch._recoveredbaskets is None:

~/Development/uproot/uproot/tree.py in _normalize_branches(self, arg, awkward, allownone, allowcallable, allowdict, allowstring, aliases)
    785         if allownone and arg is None:                      # no specification; read all branches
    786             for branch in self.allvalues():                # that have interpretations
--> 787                 interpretation = interpret(branch, awkward)
    788                 if interpretation is not None:
    789                     yield branch, interpretation

~/Development/uproot/uproot/interp/auto.py in interpret(branch, awkwardlib, swapbytes, cntvers, tobject, speedbump)
    344
    345                             try:
--> 346                                 recarray = streamerClass._recarray_dtype(cntvers=cntvers, tobject=tobject)
    347                             except (AttributeError, ValueError):
    348                                 return asgenobj(STLVector(streamerClass), branch._context, 6)

~/Development/uproot/uproot/rootio.py in _recarray_dtype(cls, cntvers, tobject)
   1371     @classmethod
   1372     def _recarray_dtype(cls, cntvers=False, tobject=True):
-> 1373         dtypesin = cls._recarray()
   1374         dtypesout = []
   1375         used = set()

~/Development/uproot/uproot/rootio.py in _recarray(cls)
      8         out.append((' vers', 'u2'))
      9         for base in cls._bases:
---> 10             out.extend(base._recarray())
     11         out.append(('algoName_', numpy.dtype('>i4')))
     12         return out

~/Development/uproot/uproot/rootio.py in _recarray(cls)
      8         out.append((' vers', 'u2'))
      9         for base in cls._bases:
---> 10             out.extend(base._recarray())
     11         raise ValueError('not a recarray')
     12         return out

~/Development/uproot/uproot/rootio.py in _recarray(cls)
     14         out.append(('phi_', numpy.dtype('>f4')))
     15         out.append(('mass_', numpy.dtype('>f4')))
---> 16         out.extend(ROOT_3a3a_Math_3a3a_PositionVector3D_3c_ROOT_3a3a_Math_3a3a_Cartesian3D_3c_double_3e203e_._recarray())
     17         out.append(('pdgId_', numpy.dtype('>i4')))
     18         out.append(('status_', numpy.dtype('>i4')))

NameError: name 'ROOT_3a3a_Math_3a3a_PositionVector3D_3c_ROOT_3a3a_Math_3a3a_Cartesian3D_3c_double_3e203e_' is not defined
```

**Comment by jpivarski** [comment] 2020-02-10 15:18
That does seem to be directly related to the previous error. The fully templated class name is translated into a Python name with `_safename`, a mostly-readable encoding of special characters defining the C++ type into a Python identifier:

https://github.com/scikit-hep/uproot/blob/dc7de0a692fa2e6cdf13d8dc79558211f7454baf/uproot/rootio.py#L687-L692

The streamer claims that a class with a particular name exists, but it doesn't; the class exists with a different name because different template parameters means a different name.

The `_recarray` function is called by the `uproot.interp.auto.interpret` function to determine if the object is fixed-width and can be cast as a NumPy array (instead of crawling more slowly over the bytes with `_readinto`). It is guaranteed that `TTree._attachstreamers` will be called before `uproot.interp.auto.interpret` because the former sets things up for the latter (and the latter is only lazily called when a user wants to know a particular branch's interpretation, anyway).

If you add an if-block in `attachstreamers` that tries an alternate name for the class and it's successful, then you can solve the downstream problem at the same time by adding the new name as an alias for the old one in the file's `_context.classes`. You don't need to recompile it; just link a new key to the same value in the `_context.classes` dict.

**Closed** 2020-02-11 16:12 UTC
Labels: bug
