### ISSUE TITLE
Error running tests

### ISSUE THREAD

**Issue by ktf** [scikit-hep/uproot#73] opened 2018-04-20 11:51 UTC
On both python 2.7 and 3.5 I get:

```
======================================================================
ERROR: test_collisions (tests.test_diskcache.TestDiskCache)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/nix-build-python2.7-uproot-2.8.16.drv-0/uproot-2.8.16/tests/test_diskcache.py", line 272, in test_collisions
    self.assertEqual(cache["/" + repr(i)][0], i)
  File "/private/tmp/nix-build-python2.7-uproot-2.8.16.drv-0/uproot-2.8.16/uproot/cache/diskcache.py", line 402, in __getitem__
    oldpath = self._get(name)  # might raise KeyError
  File "/private/tmp/nix-build-python2.7-uproot-2.8.16.drv-0/uproot-2.8.16/uproot/cache/diskcache.py", line 666, in _get
    num = json.load(collisionsfile)[urlquote(name, safe="")]
KeyError: '%2F0'

======================================================================
ERROR: test_iterators (tests.test_diskcache.TestDiskCache)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/nix-build-python2.7-uproot-2.8.16.drv-0/uproot-2.8.16/tests/test_diskcache.py", line 294, in test_iterators
    for i, value in enumerate(cache.values()):
  File "/private/tmp/nix-build-python2.7-uproot-2.8.16.drv-0/uproot-2.8.16/uproot/cache/diskcache.py", line 583, in values
    for name, obj in self.items():
  File "/private/tmp/nix-build-python2.7-uproot-2.8.16.drv-0/uproot-2.8.16/uproot/cache/diskcache.py", line 561, in items
    oldpath = self._get(name)
  File "/private/tmp/nix-build-python2.7-uproot-2.8.16.drv-0/uproot-2.8.16/uproot/cache/diskcache.py", line 666, in _get
    num = json.load(collisionsfile)[urlquote(name, safe="")]
KeyError: '%2F0'
```

**Comment by jpivarski** [comment] 2018-04-20 12:51
I'm putting in a rather draconian solution to this problem: I'm removing that suite of tests.

The diskcache is one cache option of many, and probably not widely used. (Once someone asked me, "Why would I cache on disk arrays that came out of a ROOT file on disk?" My answer was that you could have a large, slow disk with many ROOT files on it and a small, fast disk for swapping recently used data— this cache option is intended for the query system architecture that was one motivation for uproot's existence. However, that doesn't mean that these parts are useful for general users the way that uproot's core functionality of getting ROOT data into arrays is.)

The diskcache is the most environment-dependent part of uproot. I've had problems in the past where something changed on Travis and diskcache tests that used to work started failing— not in important, meaningful ways, but things like differences in the file sizes returned by system calls making eviction happen sooner or later than the test says it should.

It's not clear to me that the bug you've found (and I can't reproduce) is irrelevant in the same way, but I also don't think it's worth investigating. You can use uproot just fine without the diskcache and I'm sure most people do. Therefore, I'm removing the tests, which give a false sense that this component is important or necessary for uproot to function.

The change is committed to master. I don't need to make a new version number for PyPI because PyPI doesn't run unit tests, anyway.

**Closed by jpivarski** 2018-04-20 12:51 UTC

**Comment by ktf** [comment] 2018-04-20 19:30
Could you do a new release on PyPi nevertheless? I am packaging it for nix (https://github.com/NixOS/nixpkgs/pull/39120) and they do run the tests...

**Comment by jpivarski** [comment] 2018-04-20 19:49
I've released a new version on PyPI: [2.8.18](https://pypi.org/project/uproot/). This has the offending test removed. Reading the comments on that thread shows how environment-dependent the diskcache was: "The tests run just fine for me. Can you please check again?"

**Comment by ktf** [comment] 2018-04-20 21:00
Yeah, but they break on my Mac. Thanks.

--
Ciao,
Giulio

**Comment by jpivarski** [comment] 2018-04-20 21:10
Do you mean it's still breaking, or that it used to break on your Mac but is fine now? I just want to be sure that there aren't any other bugs.

**Comment by FRidh** [comment] 2018-04-21 05:58
Just some more info.

Nix aims for reproducible builds of packages. One of the methods to achieve this is by building in a sandbox. @ktf runs on a Mac, and runs without sandbox. @dotlambda probably runs on NixOS, and with sandbox. Without the sandbox, the build process may find certain things that cause the build or the testing to fail.
