### ISSUE TITLE
tree itervalues 'Undefined' object has no attribute 'name'

### ISSUE THREAD

**Issue by drdavis** [scikit-hep/uproot#167] opened 2018-10-18 20:38 UTC
Hi Jim,

I'm getting an error that I'm having a hard time understanding. I'm trying to access a tree in a file that is showing up if I open the file in ROOT and also if I call `allkeys()` on the uproot file. But when I try to grab the tree via the file's `__getitem__` method I get the attached error (more file details at end)

```python
In [15]: uf = uproot.open('/data/sgtop/v25_WtProcessed/wt_ntuples_elmu_ALLSYST/tW_DR_410648_FS_MC16a.root')

In [16]: uf.allkeys()
Out[16]: 
['WtLoop_nominal;1',
 'WtLoop_meta;1',              # <- it's there
 'WtLoop_EG_RESOLUTION_ALL__1down;1',
 'WtLoop_EG_RESOLUTION_ALL__1up;1',
 # ... a lot more tree names ...
 'WtLoop_MUON_SCALE__1up;1']

In [17]: uf['WtLoop_meta']
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-18-aae9cd6ceb1d> in <module>()
----> 1 uf['WtLoop_meta']

/home/ddavis/Software/Python/anaconda3/envs/py2/lib/python2.7/site-packages/uproot/rootio.pyc in __getitem__(self, name)
    225 
    226     def __getitem__(self, name):
--> 227         return self.get(name)
    228 
    229     def __len__(self):

/home/ddavis/Software/Python/anaconda3/envs/py2/lib/python2.7/site-packages/uproot/rootio.pyc in get(self, name, cycle)
    340                 if key.fName == name:
    341                     if cycle is None or key.fCycle == cycle:
--> 342                         return key.get()
    343             raise KeyError("not found: {0}".format(repr(name)))
    344 

/home/ddavis/Software/Python/anaconda3/envs/py2/lib/python2.7/site-packages/uproot/rootio.pyc in get(self, dismiss)
    847 
    848             elif classname in self._context.classes:
--> 849                 return self._context.classes[classname].read(self._source, self._cursor.copied(), self._context, self)
    850 
    851             else:

/home/ddavis/Software/Python/anaconda3/envs/py2/lib/python2.7/site-packages/uproot/rootio.pyc in read(cls, source, cursor, context, parent)
    785         out = cls.__new__(cls)
    786         out = cls._readinto(out, source, cursor, context, parent)
--> 787         out._postprocess(source, cursor, context, parent)
    788         return out
    789 

/home/ddavis/Software/Python/anaconda3/envs/py2/lib/python2.7/site-packages/uproot/tree.pyc in _postprocess(self, source, cursor, context, parent)
    250 
    251         leaf2branch = {}
--> 252         for branch in self.itervalues(recursive=True):
    253             if len(branch.fLeaves) == 1:
    254                 leaf2branch[id(branch.fLeaves[0])] = branch

/home/ddavis/Software/Python/anaconda3/envs/py2/lib/python2.7/site-packages/uproot/tree.pyc in itervalues(self, recursive, filtername, filtertitle)
    294     def itervalues(self, recursive=False, filtername=nofilter, filtertitle=nofilter):
    295         for branch in self.fBranches:
--> 296             if filtername(branch.name) and filtertitle(branch.title):
    297                 yield branch
    298             if recursive:

AttributeError: 'Undefined' object has no attribute 'name'
```

I'm not sure if this is relevant.. but the file is reopened many times to store new trees. The `WtLoop_meta` tree is a single branch, single entry tree (just one string stored in it). It also appears to be the only tree that can't be accessed

Unfortunately the file is pretty large and I can't seem to reproduce the error with a smaller test, but here it is just in case (1.6GB):
http://webhome.phy.duke.edu/~ddavis/uproot/getitem_error.root

**Comment by jpivarski** [comment] 2018-10-18 23:28
Thanks— I'll take a look. `Undefined` is a class used when uproot couldn't generate a class for some reason: it can happen for some complex types that I don't have much experience with (e.g. STL collections beyond vector and string), but it's surprising here because it looks like it's supposed to be a TBranch. (Could there be some exotic new branch type?) It's also possible that it's a standard branch but deserialization failed for some reason, in which case, the `Undefined` is a placeholder.

I hope I get a chance to look at it tomorrow, but I'm rushing to meet an unrelated deadline. If not, it could be Monday. Would that be a major problem?

**Comment by drdavis** [comment] 2018-10-19 00:28
No problem at all!

**Comment by jpivarski** [comment] 2018-10-22 17:06
Okay, the issue is that this file does not have a streamer for `TBranchElement`, and this TTree (as most TTrees of non-primitive data) has a `TBranchElement` branch. Technically, that means that the ROOT file is not self-describing, so I'd be tempted to call it a ROOT bug. The reason ROOT can read it must be because ROOT has a built-in streamer for this very important class. There's no way that can be forward-compatible (old ROOT versions can't have streamers for new ROOT versions) and it might or might not be backward-compatible (depending on how it's implemented, ROOT might only use its current streamer when one isn't found in the file).

You can see this via

```python
import uproot
f = uproot.open("tW_DR_410648_FS_MC16a.root")
f.showstreamers()   # no TBranchElement
```

I'm going to call this a feature request because conceivably, uproot could keep streamers for the past N years of a few important classes: `TTree`, `TBranch`, `TBranchElement`, and `TLeaf*`. It could even be a performance thing because we could skip reading the streamers unless we hit a class that's not built-in. But that list of streamers would always have to be updated. Going from uproot 1 to 2, I made uproot rely exclusively on streamers; this would be partly going back on that, using built-in and extracted streamers to fill in the gaps.

I'm on the fence about that.

**Comment by jpivarski** [comment] 2018-10-22 17:06
Oh, but the error message could be a bit more clear. I can do something about that, but it's too late for you.  :)

**Comment by drdavis** [comment] 2018-10-22 18:36
Thanks for the detailed explanation! This is by no means a big deal for my work (we're actually moving towards abandoning this "master file" holding all of our trees anyway) - so I wouldn't want you to sway to either side of the fence for what appears to be corner case with non primitive types.

**Comment by jpivarski** [comment] 2018-10-22 19:04
Okay, then, for now I'll close it and just keep it in the back of my mind that sometimes built-in streamers would be useful.

**Closed by jpivarski** 2018-10-22 19:04 UTC
Labels: feature-request

**Comment by drdavis** [comment] 2018-10-22 23:42
Just discovered switching to storing a `TString` instead of an `std::string` fixed the issue.
