### ISSUE TITLE
reading trees created by groot-v0.21.0

### ISSUE THREAD

**Issue by sbinet** [scikit-hep/uproot#413] opened 2019-11-28 19:50 UTC
it seems `uproot` can't read back a simple ROOT files created by Go-HEP v0.21.0:

```go
package main

import (
	"fmt"
	"log"

	"go-hep.org/x/hep/groot"
	"go-hep.org/x/hep/groot/rtree"
)

func main() {
	type Data struct {
		I32    int32
		F64    float64
		Str    string
		ArrF64 [5]float64
		N      int32
		SliF64 []float64 `groot:"SliF64[N]"` // tell ROOT/C++ the leaf name and the leaf holding the count
	}

	const (
		fname = "struct.root"
		nevts = 5
	)

	f, err := groot.Create(fname)
	if err != nil {
		log.Fatalf("%+v", err)
	}
	defer f.Close()

	var evt Data

	tree, err := rtree.NewWriter(f, "mytree", rtree.WriteVarsFromStruct(&evt))
	if err != nil {
		log.Fatalf("could not create tree writer: %+v", err)
	}

	fmt.Printf("-- created tree %q:\n", tree.Name())
	for i, b := range tree.Branches() {
		fmt.Printf("branch[%d]: name=%q, title=%q\n", i, b.Name(), b.Title())
	}

	for i := 0; i < nevts; i++ {
		evt.I32 = int32(i)
		evt.F64 = float64(i)
		evt.Str = fmt.Sprintf("evt-%0d", i)
		evt.ArrF64 = [5]float64{float64(i), float64(i + 1), float64(i + 2), float64(i + 3), float64(i + 4)}
		evt.N = int32(i)
		evt.SliF64 = []float64{float64(i), float64(i + 1), float64(i + 2), float64(i + 3), float64(i + 4)}[:i]
		_, err = tree.Write()
		if err != nil {
			log.Fatalf("could not write event %d: %+v", i, err)
		}
	}
	fmt.Printf("-- filled tree with %d entries\n", tree.Entries())

	err = tree.Close()
	if err != nil {
		log.Fatalf("could not write tree: %+v", err)
	}

	err = f.Close()
	if err != nil {
		log.Fatalf("could not close tree: %+v", err)
	}
}
```

[struct.root.gz](https://github.com/scikit-hep/uproot/files/3902913/struct.root.gz)

reading it back w/ `uproot-3.10.12` + `uproot-methods-0.7.1` yields:

```py
>>> import uproot
>>> f = uproot.open("struct.root")
>>> f["mytree"]
>>> f["mytree"]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/binet/.local/lib/python3.8/site-packages/uproot/rootio.py", line 225, in __getitem__
    return self.get(name)
  File "/home/binet/.local/lib/python3.8/site-packages/uproot/rootio.py", line 359, in get
    return last.get()
  File "/home/binet/.local/lib/python3.8/site-packages/uproot/rootio.py", line 1010, in get
    return _classof(self._context, self._fClassName).read(self._source, self._cursor.copied(), self._context, self)
  File "/home/binet/.local/lib/python3.8/site-packages/uproot/rootio.py", line 949, in read
    out = cls._readinto(out, source, cursor, context, parent)
  File "<generated from TStreamerInfo b'TTree' at 0x7fdeac430220>", line 70, in _readinto
  File "/home/binet/.local/lib/python3.8/site-packages/uproot/rootio.py", line 949, in read
    out = cls._readinto(out, source, cursor, context, parent)
  File "/home/binet/.local/lib/python3.8/site-packages/uproot/rootio.py", line 1600, in _readinto
    _endcheck(start, cursor, cnt)
  File "/home/binet/.local/lib/python3.8/site-packages/uproot/rootio.py", line 441, in _endcheck
    raise ValueError("object has {0} bytes; expected {1}".format(observed, cnt))
ValueError: object has 11 bytes; expected 7
```

reading it w/ `PyROOT-6.18/04`:
```py
>>> import ROOT
>>> f=ROOT.TFile.Open("struct.root")
>>> f.mytree.Scan()
***********************************************************************************************
*    Row   * Instance *       I32 *       F64 *       Str *    ArrF64 *         N *    SliF64 *
***********************************************************************************************
*        0 *        0 *         0 *         0 *     evt-0 *         0 *         0 *           *
*        0 *        1 *         0 *         0 *           *         1 *         0 *           *
*        0 *        2 *         0 *         0 *           *         2 *         0 *           *
*        0 *        3 *         0 *         0 *           *         3 *         0 *           *
*        0 *        4 *         0 *         0 *           *         4 *         0 *           *
*        1 *        0 *         1 *         1 *     evt-1 *         1 *         1 *         1 *
*        1 *        1 *         1 *         1 *           *         2 *         1 *           *
*        1 *        2 *         1 *         1 *           *         3 *         1 *           *
*        1 *        3 *         1 *         1 *           *         4 *         1 *           *
*        1 *        4 *         1 *         1 *           *         5 *         1 *           *
*        2 *        0 *         2 *         2 *     evt-2 *         2 *         2 *         2 *
*        2 *        1 *         2 *         2 *           *         3 *         2 *         3 *
*        2 *        2 *         2 *         2 *           *         4 *         2 *           *
*        2 *        3 *         2 *         2 *           *         5 *         2 *           *
*        2 *        4 *         2 *         2 *           *         6 *         2 *           *
*        3 *        0 *         3 *         3 *     evt-3 *         3 *         3 *         3 *
*        3 *        1 *         3 *         3 *           *         4 *         3 *         4 *
*        3 *        2 *         3 *         3 *           *         5 *         3 *         5 *
*        3 *        3 *         3 *         3 *           *         6 *         3 *           *
*        3 *        4 *         3 *         3 *           *         7 *         3 *           *
*        4 *        0 *         4 *         4 *     evt-4 *         4 *         4 *         4 *
*        4 *        1 *         4 *         4 *           *         5 *         4 *         5 *
*        4 *        2 *         4 *         4 *           *         6 *         4 *         6 *
*        4 *        3 *         4 *         4 *           *         7 *         4 *         7 *
*        4 *        4 *         4 *         4 *           *         8 *         4 *           *
***********************************************************************************************
25
```

(perhaps a `ROOT::TIOFeatures` issue?)

**Comment by jpivarski** [comment] 2019-11-29 02:33
@Arpita-Seksaria I suspect that this might be a good entry-level issue. All the detail here makes it look complicated, but I can attest that it's helpful detail. (Thanks, @sbinet!) If this really is related to `TIOFeatures`, that's a rather simple structure, though it broke pattern with streamers and had to be handled as a special case. The groot code is very readable and fast to compile, so it's easy to study if you need to follow this back to its source.

**Comment by reikdas** [comment] 2019-11-29 05:12
Perhaps there is a chance that since uproot is in some places more rigid than ROOT (especially with `_endcheck`) when reading files, this could mean that this is something that is not a bug on our side?

**Comment by jpivarski** [comment] 2019-11-29 14:48
If the new file is failing an `_endcheck` test (or similar), I think @sbinet would want to know. It would be hard to justify calling strictness about `_endcheck` a bug.

**Comment by sbinet** [comment] 2019-11-29 15:12
like ROOT, groot also counts and checks bytes upon reading.
that's why I had (by sheer inspection of binary ROOT files) to add these 4 bytes:

https://github.com/go-hep/hep/blob/18993441c8f5fbe68604f94bd834d7f745345978/groot/rtree/tree.go#L631..L681

**Comment by Arpita-Seksaria** [comment] 2019-12-01 12:17
this seems interesting @jpivarski

**Comment by jpivarski** [comment] 2019-12-01 14:39
Go for it. Open a pull request and start work there, so that we have a place to discuss it in public (not email). Prefix the pull request name with "`[WIP] `" so that it doesn't get merged accidentally, and refer to this issue by number so that the pull request and the issue get linked.

**Comment by Arpita-Seksaria** [comment] 2019-12-02 06:10
Okay, jim. Got it.

**Comment by jpivarski** [comment] 2020-07-02 03:59
This is finished in Uproot4: https://github.com/scikit-hep/uproot4/blob/fd823404093a3bae0b664665e724400add5ebb2e/tests/test_0034-generic-objects-in-ttrees.py#L1298-L1326

**Closed by jpivarski** 2020-07-02 03:59 UTC
Labels: bug, good first issue
